# This is a basic workflow to help you get started with Actions

name: Build and push the latest build to staging
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1   
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        uses: docker/login-action@v2.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ secrets.ACR_NAME }}
          # Username used to log against the Docker registry
          username: ${{ secrets.ACR_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.ACR_PASSWORD }}
         
      - name: Build and push staging images
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    steps:
      - uses: actions/checkout@v2

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          # Version of helm
          version: v3.3.1
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: mslearn-gh-pipelines-15998
          cluster-name: contoso-video 
      - name: Run Helm Deploy
        run: |
          helm upgrade \
          --install \
          --create-namespace \
          --atomic \
          --wait \
          --namespace staging \
          contoso-website \
          ./kubernetes/contoso-website \
          --set image.repository=${{ secrets.ACR_NAME }} \
          --set dns.name=${{ secrets.CLUSTER_DNS_NAME }}